theme: jekyll-theme-minimal
locale                   : "en-US"
title                    : "Muktesh's Blog"
title_separator          : "-"
subtitle                 : # site tagline that appears below site title in masthead
name                     : "Muktesh "
description              : ""
url                      : https://muktesh.dev
baseurl                  : "/dist"# the subpath of your site, e.g. "/blog"
repository               : mukteshkrmishra/mukteshkrmishra.github.io # GitHub username/repo-name e.g. "mmistakes/minimal-mistakes"
teaser                   : #/assets/images/Post-teaser.png # path of fallback teaser image, e.g. "/assets/images/500x300.png"
logo                     : # path of logo image to display in the masthead, e.g. "/assets/images/88x88.png"
masthead_title           : # overrides the website title displayed in the masthead, use " " for no title
breadcrumbs              : false # true, false (default)
