locale                   : "en-US"
title                    : "Muktesh's Blog"
title_separator          : "-"
subtitle                 : "Are you ready for the adventure?"
name                     : "Muktesh "
description              : ""
url                      : https://muktesh.dev
baseurl                  : "/dist"
repository               : mukteshkrmishra/mukteshkrmishra.github.io
breadcrumbs              : false
